# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request_review:
      types: [submitted]
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]
    #types: [closed]

jobs:
  build:
    #if: github.event.pull_request.merged == true
    #if: github.event.review.state == 'approved'
    runs-on: node:14-buster

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: apt-get update
    - run: apt-get -y install graphicsmagick imagemagick ghostscript libde265-0 libde265-dev libde265-examples libheif-dev libheif-examples libheif1 tesseract-ocr tesseract-ocr-eng tesseract-ocr-tur
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
